name: Verify

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        chmod +x ./bootstrap.sh
        ./bootstrap.sh
      shell: bash

    - name: Run tests
      run: |
        pip install tox docker-compose
        tox -e check,py39,func_test
      shell: bash